name: flutter_dev_test
description: "Developer's Flutter test"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  otp: ^3.1.4
  flutter_bloc: ^9.0.0
  go_router: ^14.8.1
  flutter_svg: ^2.0.17
  flutter_otp_text_field: ^1.5.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
